{{ if .Values.collector_proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-collector-proxy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: enterprise-collector-proxy
  template:
    metadata:
      labels:
        app: enterprise-collector-proxy
    spec:
      containers:
        - name: enterprise-collector-proxy
          image: 'semitechnologies/weaviate-enterprise-usage-collector:{{ .Values.collector_proxy.tag }}'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: weaviate_enterprise_usage_collector_origin
            value: {{ .Values.collector_proxy.weaviate_enterprise_usage_collector_origin }}
          - name: weaviate_enterprise_token
            value: {{ .Values.collector_proxy.weaviate_enterprise_token }}
          - name: weaviate_enterprise_project
            value: {{ .Values.collector_proxy.weaviate_enterprise_project }}
          volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /v1/.well-known/live
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /v1/.well-known/ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: nginx-conf
          configMap:
            name: collector-proxy-nginx-conf
{{ end }}
