{{ if index .Values "modules" "text2vec-contextionary" "enabled" }}
apiVersion: v1
kind: Service
metadata:
  name: contextionary
spec:
  type: ClusterIP
  selector:
    app: contextionary
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
{{ end }}
