apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: weaviate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
